-- AlterTable
ALTER TABLE "Org" ADD COLUMN "brandColor" TEXT NOT NULL DEFAULT '#2563eb';
ALTER TABLE "Org" ADD COLUMN "logoUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Org" ADD COLUMN "mark" TEXT NOT NULL DEFAULT 'V';
